// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumicomponentsdemo

import (
	"context"
	"reflect"

	"errors"
	"github.com/neovasili/pulumi-components-demo/sdk/go/pulumicomponentsdemo/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StorageAccountWithContainer struct {
	pulumi.ResourceState

	ContainerName       pulumi.StringOutput `pulumi:"containerName"`
	PrimaryBlobEndpoint pulumi.StringOutput `pulumi:"primaryBlobEndpoint"`
	StorageAccountId    pulumi.StringOutput `pulumi:"storageAccountId"`
	StorageAccountName  pulumi.StringOutput `pulumi:"storageAccountName"`
}

// NewStorageAccountWithContainer registers a new resource with the given unique name, arguments, and options.
func NewStorageAccountWithContainer(ctx *pulumi.Context,
	name string, args *StorageAccountWithContainerArgs, opts ...pulumi.ResourceOption) (*StorageAccountWithContainer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ContainerName == nil {
		return nil, errors.New("invalid value for required argument 'ContainerName'")
	}
	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.ResourceGroupName == nil {
		return nil, errors.New("invalid value for required argument 'ResourceGroupName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource StorageAccountWithContainer
	err := ctx.RegisterRemoteComponentResource("pulumi-components-demo:index:StorageAccountWithContainer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type storageAccountWithContainerArgs struct {
	// The name of the blob container to create
	ContainerName string `pulumi:"containerName"`
	// The Azure location for the storage account
	Location string `pulumi:"location"`
	// The Azure resource group name where the storage account will be created
	ResourceGroupName string `pulumi:"resourceGroupName"`
	// The SKU for the storage account (defaults to Standard_LRS)
	Sku *string `pulumi:"sku"`
	// Tags to apply to the storage account
	Tags map[string]string `pulumi:"tags"`
}

// The set of arguments for constructing a StorageAccountWithContainer resource.
type StorageAccountWithContainerArgs struct {
	// The name of the blob container to create
	ContainerName pulumi.StringInput
	// The Azure location for the storage account
	Location pulumi.StringInput
	// The Azure resource group name where the storage account will be created
	ResourceGroupName pulumi.StringInput
	// The SKU for the storage account (defaults to Standard_LRS)
	Sku pulumi.StringPtrInput
	// Tags to apply to the storage account
	Tags pulumi.StringMapInput
}

func (StorageAccountWithContainerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*storageAccountWithContainerArgs)(nil)).Elem()
}

type StorageAccountWithContainerInput interface {
	pulumi.Input

	ToStorageAccountWithContainerOutput() StorageAccountWithContainerOutput
	ToStorageAccountWithContainerOutputWithContext(ctx context.Context) StorageAccountWithContainerOutput
}

func (*StorageAccountWithContainer) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageAccountWithContainer)(nil)).Elem()
}

func (i *StorageAccountWithContainer) ToStorageAccountWithContainerOutput() StorageAccountWithContainerOutput {
	return i.ToStorageAccountWithContainerOutputWithContext(context.Background())
}

func (i *StorageAccountWithContainer) ToStorageAccountWithContainerOutputWithContext(ctx context.Context) StorageAccountWithContainerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StorageAccountWithContainerOutput)
}

type StorageAccountWithContainerOutput struct{ *pulumi.OutputState }

func (StorageAccountWithContainerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageAccountWithContainer)(nil)).Elem()
}

func (o StorageAccountWithContainerOutput) ToStorageAccountWithContainerOutput() StorageAccountWithContainerOutput {
	return o
}

func (o StorageAccountWithContainerOutput) ToStorageAccountWithContainerOutputWithContext(ctx context.Context) StorageAccountWithContainerOutput {
	return o
}

func (o StorageAccountWithContainerOutput) ContainerName() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageAccountWithContainer) pulumi.StringOutput { return v.ContainerName }).(pulumi.StringOutput)
}

func (o StorageAccountWithContainerOutput) PrimaryBlobEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageAccountWithContainer) pulumi.StringOutput { return v.PrimaryBlobEndpoint }).(pulumi.StringOutput)
}

func (o StorageAccountWithContainerOutput) StorageAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageAccountWithContainer) pulumi.StringOutput { return v.StorageAccountId }).(pulumi.StringOutput)
}

func (o StorageAccountWithContainerOutput) StorageAccountName() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageAccountWithContainer) pulumi.StringOutput { return v.StorageAccountName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StorageAccountWithContainerInput)(nil)).Elem(), &StorageAccountWithContainer{})
	pulumi.RegisterOutputType(StorageAccountWithContainerOutput{})
}
