// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { StorageAccountWithContainerArgs } from "./storageAccountWithContainer";
export type StorageAccountWithContainer = import("./storageAccountWithContainer").StorageAccountWithContainer;
export const StorageAccountWithContainer: typeof import("./storageAccountWithContainer").StorageAccountWithContainer = null as any;
utilities.lazyLoad(exports, ["StorageAccountWithContainer"], () => require("./storageAccountWithContainer"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pulumi-components-demo:index:StorageAccountWithContainer":
                return new StorageAccountWithContainer(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pulumi-components-demo", "index", _module)
pulumi.runtime.registerResourcePackage("pulumi-components-demo", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:pulumi-components-demo") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
