// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StorageAccountWithContainer extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'pulumi-components-demo:index:StorageAccountWithContainer';

    /**
     * Returns true if the given object is an instance of StorageAccountWithContainer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StorageAccountWithContainer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StorageAccountWithContainer.__pulumiType;
    }

    declare public readonly containerName: pulumi.Output<string>;
    declare public /*out*/ readonly primaryBlobEndpoint: pulumi.Output<string>;
    declare public /*out*/ readonly storageAccountId: pulumi.Output<string>;
    declare public /*out*/ readonly storageAccountName: pulumi.Output<string>;

    /**
     * Create a StorageAccountWithContainer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StorageAccountWithContainerArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.containerName === undefined && !opts.urn) {
                throw new Error("Missing required property 'containerName'");
            }
            if (args?.location === undefined && !opts.urn) {
                throw new Error("Missing required property 'location'");
            }
            if (args?.resourceGroupName === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceGroupName'");
            }
            resourceInputs["containerName"] = args?.containerName;
            resourceInputs["location"] = args?.location;
            resourceInputs["resourceGroupName"] = args?.resourceGroupName;
            resourceInputs["sku"] = args?.sku;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["primaryBlobEndpoint"] = undefined /*out*/;
            resourceInputs["storageAccountId"] = undefined /*out*/;
            resourceInputs["storageAccountName"] = undefined /*out*/;
        } else {
            resourceInputs["containerName"] = undefined /*out*/;
            resourceInputs["primaryBlobEndpoint"] = undefined /*out*/;
            resourceInputs["storageAccountId"] = undefined /*out*/;
            resourceInputs["storageAccountName"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StorageAccountWithContainer.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a StorageAccountWithContainer resource.
 */
export interface StorageAccountWithContainerArgs {
    /**
     * The name of the blob container to create
     */
    containerName: pulumi.Input<string>;
    /**
     * The Azure location for the storage account
     */
    location: pulumi.Input<string>;
    /**
     * The Azure resource group name where the storage account will be created
     */
    resourceGroupName: pulumi.Input<string>;
    /**
     * The SKU for the storage account (defaults to Standard_LRS)
     */
    sku?: pulumi.Input<string>;
    /**
     * Tags to apply to the storage account
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
